In [1]:
import pandas as pd

In [2]:
pd

In [4]:
cases = pd.read_csv('covid19_cases.csv')

In [5]:
cases

    country_ch        country_en       cases   deaths
0           美國     United States  34,516,883  622,158
1           印度             India  31,371,901  420,551
2           巴西            Brazil  19,688,663  549,924
3          俄羅斯            Russia   6,126,541  153,874
4           法國            France   5,993,937  111,644
..         ...               ...         ...      ...
190        萬那杜           Vanuatu           4        1
191      馬紹爾群島  Marshall Islands           4        0
192         帛琉             Palau           2        0
193        薩摩亞             Samoa           1        0
194   密克羅尼西亞聯邦        Micronesia           1        0

[195 rows x 4 columns]

In [6]:
cases_json = pd.read_json('covid19_cases.json')

In [7]:
cases_json

    country_ch        country_en       cases   deaths
0           美國     United States  34,516,883  622,158
1           印度             India  31,371,901  420,551
2           巴西            Brazil  19,688,663  549,924
3          俄羅斯            Russia   6,126,541  153,874
4           法國            France   5,993,937  111,644
..         ...               ...         ...      ...
190        萬那杜           Vanuatu           4        1
191      馬紹爾群島  Marshall Islands           4        0
192         帛琉             Palau           2        0
193        薩摩亞             Samoa           1        0
194   密克羅尼西亞聯邦        Micronesia           1        0

[195 rows x 4 columns]

In [33]:
url = 'https://www.tiobe.com/tiobe-index/'
tables = pd.read_html(url, keep_default_na=False)
tables[0].head(20)

,Oct 2022,Oct 2021,Change,Programming Language,Programming Language.1,Ratings,Change.1
0,1,1,,,Python,17.08%,+5.81%
1,2,2,,,C,15.21%,+4.05%
2,3,3,,,Java,12.84%,+2.38%
3,4,4,,,C++,9.92%,+2.42%
4,5,5,,,C#,4.42%,-0.84%
5,6,6,,,Visual Basic,3.95%,-1.29%
6,7,7,,,JavaScript,2.74%,+0.55%
7,8,10,,,Assembly language,2.39%,+0.33%
8,9,9,,,PHP,2.04%,-0.06%
9,10,8,,,SQL,1.78%,-0.39%
10,11,12,,,Go,1.27%,-0.01%
11,12,14,,,R,1.22%,+0.03%
12,13,29,,,Objective-C,1.21%,+0.76%
13,14,13,,,MATLAB,1.18%,-0.02%
14,15,17,,,Swift,1.05%,-0.06%
15,16,16,,,Ruby,0.88%,-0.24%
16,17,11,,,Classic Visual Basic,0.87%,-0.96%
17,18,20,,,Delphi/Object Pascal,0.85%,-0.09%
18,19,18,,,Fortran,0.79%,-0.29%
19,20,26,,,Rust,0.70%,+0.17%

In [10]:
student_url = "https://info.tku.edu.tw/basicdata1.aspx"

In [34]:
student_table = pd.read_html(student_url, keep_default_na=False)

In [35]:
student_table

[                                 é ç®/å­¸å¹´åº¦    108    109    110
 0                                å¤§å­¸æ¥éé¨  20273  20239  20763
 1  å¤§å­¸é²ä¿®å­¸å£«ç­åäºå¹´å¶å¨è·å°ç­   1429   1249   1146
 2     ç¢©å£«ç­ãç¢©å£«å¨è·å°ç­ååå£«ç­   2933   2721   2625
 3                    å­¸çäººæ¸åè¨ï¼äººï¼  24635  24209  24534]

In [23]:
pip install requests

Requirement already satisfied: requests in c:\users\peiyu\anaconda3\lib\site-packages (2.27.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\peiyu\anaconda3\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\peiyu\anaconda3\lib\site-packages (from requests) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\peiyu\anaconda3\lib\site-packages (from requests) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\peiyu\anaconda3\lib\site-packages (from requests) (2.0.4)
Note: you may need to restart the kernel to use updated packages.

In [24]:
import requests

In [31]:
result = requests.get("https://info.tku.edu.tw/basicdata1.aspx")

In [32]:
print(result.text)

<!doctype html>
<html>
<head>
<title>淡江大學校務及財務資訊公開專區-學生人數與變動趨勢圖</title>
<meta charset="utf-8">
<!-- Meta -->
<meta name="keywords" content="" />
<meta name="author" content="">
<meta name="robots" content="" />
<meta name="description" content="" />

<!-- this styles only adds some repairs on idevices  -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

<!-- Favicon -->
<link rel="shortcut icon" href="images/favicon.ico">

<!-- Google fonts - witch you want to use - (rest you can just remove) -->
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Roboto:100,200,300,400,500,600,700,800,900' rel='stylesheet' type='text/css'>

<!--[if lt IE 9]>
<script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!-- stylesheets -->

<link rel="stylesheet" media="screen" href="js/bootstrap/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="js/mainmenu/menu.css" type="text/css" />
<link rel="stylesheet" href="css/defaultx.css" type="text/css" />
<link rel="stylesheet" href="css/layouts.css" type="text/css" />
<link rel="stylesheet" href="css/shortcodes.css" type="text/css" />
<link rel="stylesheet" href="css/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" media="screen" href="css/responsive-leyoutsx.css" type="text/css" />
<link rel="stylesheet" type="text/css" href="css/Simple-Line-Icons-Webfont/simple-line-icons.css" media="screen" />
<link rel="stylesheet" href="css/et-line-font/et-line-font.css">
<link rel="stylesheet" href="css/optmz.css" />
<link rel="stylesheet" href="css/basicdata.css" />

<!-- Remove the below comments to use your color option -->
<!--<link rel="stylesheet" href="css/colors/lightblue.css" />-->
<!--<link rel="stylesheet" href="css/colors/orange.css" />-->
<!--<link rel="stylesheet" href="css/colors/green.css" />-->
<!--<link rel="stylesheet" href="css/colors/pink.css" />-->
<!--<link rel="stylesheet" href="css/colors/red.css" />-->
<!--<link rel="stylesheet" href="css/colors/purple.css" />-->
<!--<link rel="stylesheet" href="css/colors/bridge.css" />-->
<!--<link rel="stylesheet" href="css/colors/yellow.css" />-->
<!--<link rel="stylesheet" href="css/colors/violet.css" />-->
<!--<link rel="stylesheet" href="css/colors/cyan.css" />-->
<!--<link rel="stylesheet" href="css/colors/mossgreen.css" />-->
<style type="text/css">
@media only screen and (max-width:999px) and (min-width:480px){
	.table-style-2 td:nth-of-type(1):before { content: ""; }
	.table-style-2 td:nth-of-type(2):before { content: "(108學年度) "; }
	.table-style-2 td:nth-of-type(3):before { content: "(109學年度) "; }
	.table-style-2 td:nth-of-type(4):before { content: "(110學年度) "; }

}
@media only screen and (max-width: 479px){
	.table-style-2 td:nth-of-type(1):before { content: ""; }
	.table-style-2 td:nth-of-type(2):before { content: "(108學年度) "; }
	.table-style-2 td:nth-of-type(3):before { content: "(109學年度) "; }
	.table-style-2 td:nth-of-type(4):before { content: "(110學年度) "; }

}

</style>
</head>

<body>
<div class="site_wrapper">
    <div class="topbar orange2 topbar-padding">

  </div>
  <div class="clearfix"></div>

  <div id="header">
    <div class="container">
      <div class="navbar navbar-default yamm dark2">
        <div class="navbar-header">
          <button type="button" data-toggle="collapse" data-target="#navbar-collapse-grid" class="navbar-toggle two three"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>

        </div>
        <div id="navbar-collapse-grid" class="navbar-collapse collapse pull-right">
          <ul class="nav navbar-nav">


            <li class="dropdown"> <a href="option1.aspx" class="dropdown-toggle">校務資訊說明</a>
              <ul class="dropdown-menu" role="menu">
                	<li><a href="intro.aspx">學校沿革</a> </li>
                    <li><a href="https://about.tku.edu.tw/organize.html" target='_blank'> 組織架構</a> </li>

                    <li class="dropdown-submenu mul"> <a tabindex="-1" href="#">基本數據及趨勢 + </a>
                      <ul class="dropdown-menu">
                        <li><a href="basicdata1.aspx">學生人數與變動趨勢圖</a></li>
                        <li><a href="basicdata2.aspx">教職員人數與變動趨勢圖</a></li>
                        <li><a href="basicdata3.aspx">生師比與變動趨勢圖</a></li>
                        <li><a href="basicdata4.aspx">每生校地及校舍面積</a></li>
                        <li><a href="basicdata5.aspx">學校圖書資源</a></li>
                        <li><a href="basicdata6.aspx">學校設備與資源</a></li>
                      </ul>
                    </li>

                    <li><a href="prospect.aspx"> 學校特色與發展願景</a> </li>
                    <li class="dropdown-submenu mul"><a tabindex="-1" href="#"> 學校績效表現 + </a>
                      <ul class="dropdown-menu">
                        <li><a href="effects1.aspx">各類評鑑結果</a></li>
                        <li><a href="effects2.aspx">各項績效表現</a></li>
                        <li><a href="effects3.aspx">畢業生流向與校友表現</a></li>
                       </ul>
                    </li>
                    <li><a href="https://about.tku.edu.tw/trustees/index.asp" target="_blank" title="連結董事會專區(另開視窗)">私立學校董事會相關資訊</a> </li>

              </ul>
            </li>

            <li class="dropdown"> <a href="option2.aspx" class="dropdown-toggle">財務資訊分析</a>
              <ul class="dropdown-menu" role="menu">
                	<li><a href="in_out_analy.aspx">學校收入分析</a> </li>
                    <li><a href="in_out_analy2.aspx">學校支出分析</a> </li>
              </ul>
            </li>

            <li class="dropdown"> <a href="option3.aspx" class="dropdown-toggle">學雜費與就學補助資訊</a>
              <ul class="dropdown-menu" role="menu">
                	<li><a href="allowance.aspx">學雜費收費標準</a> </li>
                    <li><a href="allowance2.aspx">平均教學成本</a> </li>
                    <li><a href="allowance3.aspx">學雜費佔教學成本比率</a> </li>
                    <li><a href="allowance4.aspx">在學期間教育支出估算</a> </li>
                    <li><a href="allowance5.aspx">各項助學措施資訊</a> </li>
                    <li><a href="allowance6.aspx">就學貸款/獎助學金/學雜費減免</a> </li>
                    <li><a href="use_layout.aspx">學雜費調整之用途規劃說明</a> </li>
                    <li><a href="discussion.aspx">學雜費調整校內審議程序說明</a> </li>
              </ul>
            </li>

            <li class="dropdown"> <a href="option4.aspx" class="dropdown-toggle">學校其他重要資訊</a>
              <ul class="dropdown-menu three" role="menu">
                <li> <a href="budget.aspx">預算編審程序</a> </li>
                <li> <a href="report.aspx">會計師查核報告</a> </li>
                <li> <a href="purchase.aspx">學校採購情形</a> </li>
                <li> <a href="handle.aspx">處分土地及重大資產</a> </li>
                <li> <a href="course.aspx">課程與師資</a> </li>
                <li> <a href="others.aspx">其他</a> </li>
              </ul>
            </li>
            <li class="dropdown"> <a href="option5.aspx" class="dropdown-toggle">內控內稽執行情形</a>
              <ul class="dropdown-menu two" role="menu">
                <li> <a href="doc/control.pdf" target="_blank">內部控制制度手冊 </a></li>
                <li> <a href="audit.aspx">內部控制制度作業程序</a> </li>
                <li> <a href="audit_point.aspx">內部控制重點</a> </li>
                <li> <a href="audit_rule.aspx">內部稽核作業規範</a> </li>
                <li> <a href="audit_report.aspx">稽核計畫及稽核報告</a> </li>
              </ul>
            </li>
            <li class="dropdown"> <a href="https://about.tku.edu.tw/trustees/index.asp" target="_blank" title="連結董事會專區(另開新視窗)">董事會相關資訊</a></li>

          </ul>
        </div>
      </div>
    </div>
  </div>
  <!--end menu-->


  <section>
    <div class="header-inner two">
      <div class="inner text-center">
        <h4 class="title text-white uppercase">校務資訊說明</h4>
<!--        <h5 class="text-white uppercase">Get Many More Features</h5>-->
      </div>
      <div class="overlay bg-opacity-5"></div>
<!--      <img src="images/header-img1.jpg" alt="" class="img-responsive"/> -->
      </div>
  </section>
  <!-- end header inner -->
  <div class="clearfix"></div>

  <section>
    <div class="pagenation-holder">
      <div class="container">

        <div class="row">
          <div class="col-md-6">
            <h3>學生人數與變動趨勢圖</h3>
          </div>
          <div class="col-md-6 text-right">
            <div class="pagenation_links"><a href="index.aspx" title="回首頁"><i class="fa fa-home"></i></a><i> / </i> <a href="option1.aspx" title="回校務資訊說明選單">校務資訊說明</a> <i> / </i> <a href="basicdata.aspx" title="回基本數據及趨勢次選單">基本數據及趨勢</a> <i> / </i> 學生人數</div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--end section-->
  <div class="clearfix"></div>

 <section class="sec-padding">
    <div class="container">
      <div class="row">

        <div class="table-holder">
          <h3 class="section-title"><span class="text-orange-5">近3年學生人數</span></h3>
<!--        <div class="domain-pricing-table-holder">-->

          <table class="table-style-2 table-bordered">
            <thead>
              <tr>
                <th>項目/學年度</th>
                <th>108</th>
                <th>109</th>
                <th>110</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><div class="padding-left-1">大學日間部</div></td>
                <td><div class="text-right">20,273</div></td>
                <td><div class="text-right">20,239</div></td>
                <td><div class="text-right">20,763</div></td>
              </tr>
              <tr>
                <td><div class="padding-left-1">大學進修學士班及二年制在職專班</div></td>
                <td><div class="text-right">1,429</div></td>
                <td><div class="text-right">1,249</div></td>
                <td><div class="text-right">1,146</div></td>
              </tr>
              <tr>
                <td><div class="padding-left-1">碩士班、碩士在職專班及博士班</div></td>
                <td><div class="text-right">2,933</div></td>
                <td><div class="text-right">2,721</div></td>
                <td><div class="text-right">2,625</div></td>
              </tr>
              <tr class="subtotl">
                <td>學生人數合計（人） </td>
                <td><div class="text-right">24,635</div></td>
                <td><div class="text-right">24,209</div></td>
                <td><div class="text-right">24,534</div></td>
              </tr>
            </tbody>
          </table>
          <p class="text-red text-right">資料日期：每學年10月15日報部資料</p>
        </div>
      </div>
    </div>
  </section>
  <div class="clearfix"></div>
  <!-- end section -->


  <section class="sec-moreless-padding ">
  <div id="orgchart-section">
    <div class="container">

      <div class="row">

        <div class="content margin-top3">
          <h3 class="section-title"><span class="text-orange-5">近3年學生人數變動趨勢圖</span></h3>

            <img src="images/1-3-1.png" class="img-responsive col-centered" alt="近3年學生人數變動趨勢圖" title="近3年學生人數變動趨勢圖" />

        </div>
      </div>



    </div>
  </div>
  </section>
  <div class="clearfix"></div>
  <!-- end section -->

    <section class="footer section-fulldark sec-moreless-padding">
    <div class="container">
      <div class="row myfoot">
        <div class="col-md-4 col-sm-6 colmargin clearfix">
          <h6 class="uppercase footer-title less-mar3">資料維護</h6>
          <div class="footer-title-bottomstrip"></div>
          <div class="clearfix"></div>
          <ul class="address-info no-border">
            <li><i class="fa fa-pencil"></i> <a href="http://www.ac.tku.edu.tw/" target="_blank" title="連結秘書處網頁(另開視窗)">秘書處</a> 江雅玲、<a href="http://www.finance.tku.edu.tw/" target="_blank" title="連結財務處網頁(另開視窗)">財務處</a> 巫佩樺</li>

          </ul>
        </div>
        <!--end item-->

        <div class="col-md-3 col-sm-6 colmargin clearfix">
          <h6 class="uppercase footer-title less-mar3">網站建置</h6>
          <div class="footer-title-bottomstrip"></div>
          <div class="clearfix"></div>
          <ul class="address-info no-border">
            <li><i class="fa fa-gear"></i> <a href="http://www.ipc.tku.edu.tw" target="_blank" title="連結資訊處網頁(另開視窗)">資訊處</a> 張秀榕</li>
          </ul>
        </div>
        <!--end item-->

        <div class="col-md-3 col-sm-6 colmargin tex-left clearfix">
          <h6 class="uppercase footer-title less-mar3">更新日期</h6>
          <div class="footer-title-bottomstrip"></div>
          <div class="clearfix"></div>
          <ul class="usefull-links tex-left no-border">
            <li><i class="fa fa-calendar"></i>  2022-10-27</li>
          </ul>
        </div>
        <!--end item-->

        <div class="col-md-2 col-sm-6 colmargin tex-left clearfix">

          <span class="pull-right"><a href="https://www.tku.edu.tw" target="_blank" title="回淡江大學首頁"><img src="images/TKU-logo.png" class="img-responsive" /></a></span>

        </div>
        <!--end item-->

      </div>
    </div>
  </section>
  <!--end section-->
  <div class="clearfix"></div>

  <section class="section-copyrights sec-minless-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="clearfix"></div>

          <p><span>淡江大學 版權所有 Copyright©2018 Tamkang University All rights reserved.</span></p>
		 </div>
      </div>
    </div>
  </section>
  <a href="#" class="scrollup"></a><!-- end scroll to top of the page-->


</div>
<!--end sitewraper-->

<!-- ========== Js files ========== -->

<script type="text/javascript" src="js/universal/jquery.js"></script>
<script src="js/bootstrap/bootstrap.min.js" type="text/javascript"></script>
<script src="js/mainmenu/customeUI.js"></script>
<script src="js/mainmenu/jquery.sticky.js"></script>
<script src="js/scrolltotop/totop.js"></script>

<script src="js/scripts/functions.js" type="text/javascript"></script>

</body>
</html>